# Generated by Django 2.1.1 on 2018-09-07 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feiraslivres',
            options={'ordering': ['id'], 'verbose_name': 'Feira Livre em SP', 'verbose_name_plural': 'Feiras Livres em SP'},
        ),
    ]
